stages:
  - deploy

workflow:
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
    # Allow run pipeline on Develop branch only
    - if: '$CI_COMMIT_BRANCH == "develop"'
    - if: $CI_COMMIT_TAG

deploy:
  stage: deploy
  image:
    name: adiii717/docker-sfdx-cli:latest
    entrypoint: [""]
  tags:
    - kubernetes
  script:
    # Save SERVER_KEY in the Gitlab environment variable
    - echo "${SERVER_KEY}" > server.key
    - sfdx auth:jwt:grant 
      --clientid $SF_CONSUMER_KEY 
      --jwtkeyfile server.key 
      --username $SF_USERNAME 
      --instanceurl https://test.salesforce.com 
      --setalias QA
    - sfdx force:source:deploy 
      --manifest ./src/package.xml --json 
      -u QA
  rules:
    - if: '$CI_COMMIT_BRANCH == "develop"'
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
