#
# Download the SFDX CLI and install it
#
before_script:
  # Decrypt server key
  - openssl aes-256-cbc -d -md md5 -in assets/server.key.enc -out assets/server.key -k $SERVER_KEY_PASSWORD

  # Setup SFDX environment variables
  - export CLIURL=https://developer.salesforce.com/media/salesforce-cli/sfdx-linux-amd64.tar.xz  
  - export SFDX_AUTOUPDATE_DISABLE=false
  - export SFDX_USE_GENERIC_UNIX_KEYCHAIN=true
  - export SFDX_DOMAIN_RETRY=300
  - export SFDX_DISABLE_APP_HUB=true
  - export SFDX_LOG_LEVEL=DEBUG
  - export DEPLOYDIR=src
  - export TESTLEVEL=RunLocalTests

  #Create SFDX directory
  - mkdir sfdx

  #Install Salesforce CLI 
  - wget -qO- $CLIURL | tar xJ -C sfdx --strip-components 1
  - "./sfdx/install"
  - export PATH=./sfdx/$(pwd):$PATH

  # Output SFDX version and plugin information
  - sfdx --version
  - sfdx plugins --core

#
# The script step will authenticate to the target deployment org and deploy the metadata.
#
deploy: 
  script:
  # Authorize target deployment org
  - sfdx force:auth:jwt:grant --instanceurl https://test.salesforce.com --clientid $SF_CONSUMER_KEY --jwtkeyfile assets/server.key --username $SF_USERNAME --setalias UAT 

  # Deploy to target deployment org and run unit tests
  - sfdx force:mdapi:deploy --wait 10 --deploydir $DEPLOYDIR --targetusername UAT --testlevel $TESTLEVEL

  # Example shows how to run a check only deploy
  #- sfdx force:mdapi:deploy --checkonly --wait 10 --deploydir $DEPLOYDIR --targetusername UAT --testlevel $TESTLEVEL